### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by Rufnas29** [GlennFolker/beautiful#2]
This is either a virus or a mistake because I cant play mindustry anymore

**Comment by Rufnas29** [comment]
Please delete this it is my favorite game and I cannot delete this mod that crashes me. :(

**Comment by XxsuperdeadlysniperxX** [comment]
GLENN YOU IDIOT Why Make A Mod That Intentionally PermCrashs Mindustry  I Want To Report This To Github As MaLiCiOuS cuz you are a bad person GlEnN also github doesn't allow malicious code on their site

**Comment by GlennFolker** [comment]
> because I cant play mindustry anymore

According to my codes, they're just stupid event listener hooks that brings you to a rickroll site as well as triggering you with annoying conditions, therefore that should never happen unless you **manually** delete the mod from `/Mindustry/mods`.

> I cannot delete this mod that crashes me. :(

What did I say earlier?
