### ISSUE TITLE
Glenn you made basically malicious mod which would technically be malware because it is intended to crash mindustry as soon as the mods load which causes a loop (either update this mod or kill the mod)

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [GlennFolker/beautiful#6]
This loop then gets annoying and people get angry because they have to reinstall mindustry because of it which in turn they lose their data either by accident or out of curiosity so @GlennFolker if this is not removed i will report this mod to github **_because intentionally crashing games with a rickroll before the permcrash is punishable by github and is considered malicious as well as malicious intent cuz for all we know this could be actual malware and you could have infected a fuck load of people with it which BREAKS GITHUBS RULES_**

**Comment by XxsuperdeadlysniperxX** [comment]
And not to mention that it says the _best_ content with is also a scam so even if it wasn't malicious it still breaks the rules as this is misleading information

**Comment by XxsuperdeadlysniperxX** [comment]
@GlennFolker github might ban you and delete this if they find it malicious just a fair warning

**Comment by XxsuperdeadlysniperxX** [comment]
If you aren't aware as of yet
1. You are solely responsible for the content of, and for any harm resulting from, any User-Generated Content that you post, upload, link to or otherwise make available via the Service, regardless of the form of that Content
2. (Github) We have the right to refuse or remove any User-Generated Content that, in our sole discretion, violates any laws or GitHub terms or policies. User-Generated Content displayed on GitHub for mobile may be subject to mobile app stores' additional terms.

**Comment by XxsuperdeadlysniperxX** [comment]
Thats the most important yet most of the terms have truncated cuz of either not related or unimportant
_see Terms Of Service in the settings for more_

**Comment by GlennFolker** [comment]
![image](https://user-images.githubusercontent.com/63218676/114165349-8e62aa00-9956-11eb-9fcf-bf2a5fda31c5.png)
Either you have a really bad device or you're just trying to mess with me, but I have made it less laggy and more playable regardless.

**Comment by XxsuperdeadlysniperxX** [comment]
I was thrown in to a crash loop

**Comment by XxsuperdeadlysniperxX** [comment]
Its not my device cuz i can use every other mod except for this one
