### ISSUE TITLE
You have no right to say this works for android

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [GlennFolker/beautiful#8]
![Screenshot_20210509-183704_Mindustry.jpg](https://user-images.githubusercontent.com/63037076/117590549-a6644f80-b0f5-11eb-8fe9-caa8b2bd138e.jpg)

This crash is the result of this mod specifically all i did was import via github

This is technically violating githubs tos as this will put my game into a crash loop and sometimes crash my entire phone this will be reported

**Comment by XxsuperdeadlysniperxX** [comment]
Oh and btw my phone isn't bad

**Comment by XxsuperdeadlysniperxX** [comment]
Your giving people attitude as well

**Comment by XxsuperdeadlysniperxX** [comment]
![Screenshot_20210509-185448_YouTube.jpg](https://user-images.githubusercontent.com/63037076/117591048-18d62f00-b0f8-11eb-96fd-fdac5f9771e5.jpg)

Already found one problem

**Comment by XxsuperdeadlysniperxX** [comment]
This might be a cause of the crash if your trying to place an unavailable video on screen another is the way you talk to people you very clearly didn't attempt to fix issue


**_fix your attitude plz cuz its unbelievably annoying to get a single thing across to a person with a rotten personality_**

**Comment by GlennFolker** [comment]
> This might be a cause of the crash if your trying to place an unavailable video on screen

What in the **absolute fuck** is wrong with your wrinkless brain? Do you not have the ability to read scripts? Or are you just trying to frame me? I don't know and I don't care, and I have fucking updated it *long ago* to make it less laggy and more playable you moron.

**Comment by XxsuperdeadlysniperxX** [comment]
Telling me off won't save you btw and you still haven't looked at the tos
of github
