### ISSUE TITLE
Your attitude is what get you banned for sure

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [GlennFolker/beautiful#9]
Don't call people idiots cuz harrassment is a violation of tos lol

**Comment by XxsuperdeadlysniperxX** [comment]
Why the heck would you make this mod even public if it doesn't work

**Comment by GlennFolker** [comment]
Okay genius, now try out [this mod](https://github.com/QmelZ/computer-begone) and rant the hell out about your device breaking. I am entirely sure the owner won't take the ordeal out just like me.

**Comment by XxsuperdeadlysniperxX** [comment]
For one i have a phone two why the hell would that mad exist three that i
sure will crash my device aka is (malicious) this defined as characterized
by malice; intending or intended to do harm because the mod causes a crash
it is defined as doing harm which once again is against github's tos which
can can get the mod and possibly even your account banned i even posted
almost the entire tos in the comments

**Comment by XxsuperdeadlysniperxX** [comment]
Still crashs me lol you updated the link your mod definitely conflicts with something in the game and thus causes a crash loop
